Controllers/NavigationController.cs
using MarkRestaurant.Data.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MarkRestaurant.Controllers
{
    public class NavigationController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ProductRepository _productRepository;

        public NavigationController(
            UserManager<User> userManager,
            ProductRepository productRepository
        )
        {
            _userManager = userManager;
            _productRepository = productRepository;
        }

        private async Task<User?> GetUserByEmailAsync(string email)
        {
            return await _userManager.FindByEmailAsync(email);
        }

        #region  Logged

        [HttpPost]
        public async Task<IActionResult> LIndex(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return View("~/Views/Logged/LoggedIndex.cshtml", user);
        }
        [HttpPost]
        public async Task<IActionResult> LMenu(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return View("~/Views/Logged/LoggedMenu.cshtml", user);
        }
        [HttpPost]
        public async Task<IActionResult> LAbout(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return View("~/Views/Logged/LoggedAbout.cshtml", user);
        }
        [HttpPost]
        public async Task<IActionResult> LBookTable(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return View("~/Views/Logged/LoggedBookTable.cshtml", user);
        }
        
        [HttpPost]
        public async Task<IActionResult> Edit(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return View("~/Views/Account/UserEdit.cshtml", user);
        }
        [HttpPost]
        public async Task<IActionResult> EnterIn(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return View("~/Views/Account/User.cshtml", user);
        }
        [HttpPost]
        public async Task<IActionResult> Basket(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return View("~/Views/Account/Basket.cshtml", user);
        }
        [HttpPost]
        public async Task<IActionResult> ResetPasswordView(string email)
        {
            var user = await GetUserByEmailAsync(email);
            return RedirectToAction("ResetPasswordView", user);
        }

        #endregion

        #region Admin 

        public IActionResult AdminAddProduct() => View("~/Views/Admin/AdminAddProduct.cshtml");
        public IActionResult AdminDashboard() => View("~/Views/Admin/AdminDashboard.cshtml");
        public IActionResult AdminMenu() => View("~/Views/Admin/AdminMenu.cshtml");
        public async Task<IActionResult> AdminUsers()
        {
            var users = await _userManager.Users.ToListAsync();
            return View("~/Views/Admin/AdminUsers.cshtml", users);
        }

        #endregion

        #region Email 

        public IActionResult ResetPasswordView() => View("~/Views/Auth/ResetPasswordView.cshtml");
        public IActionResult EmailConfirm() => View("~/Views/Auth/EmailConfirm.cshtml");
        public IActionResult ConfirmEmailSucces() => View("~/Views/Auth/ConfirmEmailSucces.cshtml");
        public IActionResult ForgotPassword() => View("~/Views/Auth/ForgotPassword.cshtml");
        public IActionResult ResetPasswordSucces() => View("~/Views/Auth/ResetPasswordSucces.cshtml");

        #endregion
        
    }
}

Controllers/UserController.cs
using MarkRestaurant.Data.Repository;
using MarkRestaurant.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MarkRestaurant.Controllers
{
    public class UserController : Controller
    {
        private readonly ProductRepository _productRepository;
        private readonly OrderRepository _basketRepository;
        private readonly UserManager<User> _userManager;
        private readonly IEmailSender _emailSender;

        public UserController(
            OrderRepository basketRepository,
            UserManager<User> userManager,
            ProductRepository productRepository,
            IEmailSender emailSender
        )
        {
            _productRepository = productRepository;
            _basketRepository = basketRepository;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        private async Task<User?> GetUserByEmailAsync(string email)
        {
            return await _userManager.FindByEmailAsync(email);
        }

        [HttpPost]
        public async Task<IActionResult> AddToBasket(string productId, string email)
        {
            var user = await GetUserByEmailAsync(email);
            var product = await _productRepository.GetProductById(Guid.Parse(productId));

            if (user == null || product == null)
            {
                return View("Error", new ErrorViewModel("Error", "The user or product was not found."));
            }

            await _basketRepository.AddOrderToOrders(product, user);

            return View("~/Views/Logged/LoggedMenu.cshtml", user);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveProductFromBasket(Guid productId, string email)
        {
            var user = await GetUserByEmailAsync(email);

            if (user == null)
            {
                return View("Error", new ErrorViewModel("Error", "The user or product was not found."));
            }

            await _basketRepository.RemoveProductFromBasket(productId, user.Id);

            return View("~/Views/Account/Basket.cshtml", user);
        }

        [HttpPost]
        public async Task<IActionResult> ClearProductsInBasket(string email)
        {
            var user = await GetUserByEmailAsync(email);

            if (user == null)
            {
                return View("Error", new ErrorViewModel("Error", "The user or product was not found."));
            }

            await _basketRepository.ClearProductsByUser(user.Id);

            return View("~/Views/Account/Basket.cshtml", user);
        }

        [HttpPost]
        public async Task<IActionResult> FinishOrder(string email, double totalPrice)
        {
            var user = await GetUserByEmailAsync(email);

            if (user == null)
            {
                return View("Error", new ErrorViewModel("Error", "The user or product was not found."));
            }

            var orders = await _basketRepository.FinishOrder(user.Id);
            if (orders == null || !orders.Any())
            {
                return View("Error", new ErrorViewModel("Error", "Order could not be completed."));
            }

            var orderNumber = GenerateOrderNumber();

            await _emailSender.SendReceiptEmailAsync(email, "Your Receipt from Mark Restaurant", orderNumber, user.Name, orders, totalPrice);

            return View("~/Views/Logged/LoggedIndex.cshtml", user);
        }

        [HttpPost]
        public async Task<IActionResult> Save(string email, string name, string surname, string middleName, int age, string phoneNumber)
        {
            var user = await GetUserByEmailAsync(email);

            if (string.IsNullOrWhiteSpace(email) || string.IsNullOrWhiteSpace(name) ||
                string.IsNullOrWhiteSpace(surname) || string.IsNullOrWhiteSpace(phoneNumber))
            {
                return View("~/Views/Account/UserEdit.cshtml", user);
            }

            user.Name = name;
            user.Surname = surname;
            user.MiddleName = middleName;
            user.Age = age;
            user.PhoneNumber = phoneNumber;

            var updateResult = await _userManager.UpdateAsync(user);

            if (updateResult.Succeeded)
            {
                return View("~/Views/Account/User.cshtml", user);
            }

            return View("~/Views/Account/UserEdit.cshtml", user);
        }

        private string GenerateOrderNumber()
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            Random random = new Random();

            return "#" + new string(Enumerable.Repeat(chars, 7)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}

Views/Shared/Logs/_LUser.cshtml
<form method="post" asp-controller="Navigation" asp-action="EnterIn" class="d-inline">
    <input type="hidden" name="email" value="@Model.UserName" />
    <button type="submit" class="user_l">
        @Model.Name
    </button>
</form>

<div id="cart-link" class="cart-link">
    <form method="post" asp-controller="Navigation" asp-action="Basket" class="d-inline">
        <input type="hidden" name="email" value="@Model.UserName" />
        <button type="submit" class="btn btn-link p-0">
            <i class="fa fa-shopping-cart"></i>
        </button>
    </form>
</div>

Views/Shared/Logs/_LogMenu.cshtml
@using MarkRestaurant.Data;
@using MarkRestaurant.Data.Repository;
@using MarkRestaurant.Models;
@using Microsoft.EntityFrameworkCore;
@inject ProductRepository productRepository

<div class="container">
        <div class="heading_container heading_center">
            <h2>
                Our Menu
            </h2>
        </div>

        <div class="filter-container">
            <ul class="filter-list">
                <li class="flist-item active" data-category="All">All</li>
                <li class="flist-item" data-category="Burgers">Burgers</li>
                <li class="flist-item" data-category="Potato">Potato</li>
                <li class="flist-item" data-category="Snacks">Snacks</li>
                <li class="flist-item" data-category="Drinks">Drinks</li>
            </ul>
        </div>

        <div class="products">
            @foreach (var product in productRepository.GetAllProducts().Result)
            {
                <div class="product @product.Category">
                    <img src="@product.ImageUrl" alt="@product.Title">
                    <div class="product-info">
                        <h3>@product.Title</h3>
                        <p>₼@product.Price</p>

                        <form method="post" asp-controller="User" asp-action="AddToBasket" >
                            <input type="hidden" name="email" value="@Model.UserName"/>
                            <input type="hidden" name="productId" value="@product.Id"/>
                            <button type="submit" class="cart-button" style="padding: 8px 13px;">
                                <i class="fa fa-shopping-cart"></i>
                            </button>
                        </form>
                    </div>
                </div>
            }
        </div>
</div>